In [1]:
import pandas as pd
import numpy as np

In [3]:
dfMEAN = pd.read_excel(r'./Data/Excel/MEAN_24_04_2024.xlsx')
dfMVKE = pd.read_excel(r'./Data/Excel/MVKE_24_04_24_Filtrado.xlsx')

In [6]:
dfJoin = dfMEAN.merge(dfMVKE, on=['Material'], how="outer", indicator=True)

In [7]:
dfJoin.head()

,Material,Unidad med.visualiz.,Número actual,Código EAN/UPC,Tipo EAN,Ind.EAN principal,Concat,Organización ventas,Organización ventas descripción,País Org Venta,Canal distribución,PB CadenDistribución,Grupo de materiales,Grupo de materiales descripción,_merge
0,102005,BOT,1.0,5.029704e+12,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P1,NaN,RI,Gordon Grahams Islay,both
1,102005,BOT,1.0,5.029704e+12,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P2,NaN,RI,Gordon Grahams Islay,both
2,102005,BOT,1.0,5.029704e+12,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P3,NaN,RI,Gordon Grahams Islay,both
3,102005,CJ,1.0,5.029705e+12,HE,X,CJ5029704701674,PRAU,Proximo Australia,AU,P1,NaN,RI,Gordon Grahams Islay,both
4,102005,CJ,1.0,5.029705e+12,HE,X,CJ5029704701674,PRAU,Proximo Australia,AU,P2,NaN,RI,Gordon Grahams Islay,both

In [4]:
dfMVKE.head()

,Material,Organización ventas,Organización ventas descripción,País Org Venta,Canal distribución,PB CadenDistribución,Grupo de materiales,Grupo de materiales descripción
0,4,CC01,Ventas Nacional,MX,10,NaN,93,San Viuda De Sanchez
1,4,CC01,Ventas Nacional,MX,20,NaN,93,San Viuda De Sanchez
2,4,CC01,Ventas Nacional,MX,40,NaN,93,San Viuda De Sanchez
3,4,CC01,Ventas Nacional,MX,60,NaN,93,San Viuda De Sanchez
4,134,CC01,Ventas Nacional,MX,10,NaN,03,1800 Añejo

In [5]:
dfMEAN.head()

,Material,Unidad med.visualiz.,Número actual,Código EAN/UPC,Tipo EAN,Ind.EAN principal,Concat
0,4,BOT,1,7.501035e+12,HE,X,BOT7501035025011
1,4,CJ,1,2.750104e+13,IC,X,CJ27501035025015
2,134,BOT,1,7.501035e+12,HE,X,BOT7501035025011
3,4160,BOT,1,7.501035e+12,HE,X,BOT7501035010741
4,4160,CJ,1,2.750104e+13,IC,X,CJ27501035012145

In [9]:
dfJoin =dfJoin.astype(str)

In [10]:
dfJoin.to_excel(r'./Data/Excel/MEAN_LO_Join_MVKE_24_04_2024.xlsx', index=False)

In [11]:
dfJoin.head()

,Material,Unidad med.visualiz.,Número actual,Código EAN/UPC,Tipo EAN,Ind.EAN principal,Concat,Organización ventas,Organización ventas descripción,País Org Venta,Canal distribución,PB CadenDistribución,Grupo de materiales,Grupo de materiales descripción,_merge
0,102005,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P1,nan,RI,Gordon Grahams Islay,both
1,102005,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P2,nan,RI,Gordon Grahams Islay,both
2,102005,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,PRAU,Proximo Australia,AU,P3,nan,RI,Gordon Grahams Islay,both
3,102005,CJ,1.0,5029704701674.0,HE,X,CJ5029704701674,PRAU,Proximo Australia,AU,P1,nan,RI,Gordon Grahams Islay,both
4,102005,CJ,1.0,5029704701674.0,HE,X,CJ5029704701674,PRAU,Proximo Australia,AU,P2,nan,RI,Gordon Grahams Islay,both

In [12]:
dfJoinInverse = dfMVKE.merge(dfMEAN, on=['Material'], how="outer", indicator=True)

In [13]:
dfJoinInverse =dfJoinInverse.astype(str)

In [14]:
dfJoinInverse.head()

,Material,Organización ventas,Organización ventas descripción,País Org Venta,Canal distribución,PB CadenDistribución,Grupo de materiales,Grupo de materiales descripción,Unidad med.visualiz.,Número actual,Código EAN/UPC,Tipo EAN,Ind.EAN principal,Concat,_merge
0,102005,PRAU,Proximo Australia,AU,P1,nan,RI,Gordon Grahams Islay,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,both
1,102005,PRAU,Proximo Australia,AU,P1,nan,RI,Gordon Grahams Islay,CJ,1.0,5029704701674.0,HE,X,CJ5029704701674,both
2,102005,PRAU,Proximo Australia,AU,P2,nan,RI,Gordon Grahams Islay,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,both
3,102005,PRAU,Proximo Australia,AU,P2,nan,RI,Gordon Grahams Islay,CJ,1.0,5029704701674.0,HE,X,CJ5029704701674,both
4,102005,PRAU,Proximo Australia,AU,P3,nan,RI,Gordon Grahams Islay,BOT,1.0,5029704111442.0,HE,X,BOT5029704111442,both

In [15]:
dfJoinInverse.to_excel(r'./Data/Excel/MVKE_LO_Join_MEAN_24_04_2024.xlsx', index=False)